services:
  app:
    build: .
    env_file:
      - app.env
    depends_on:
      - postgres
    ports:
      - "8080:8080"
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 6500:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
volumes:
  postgres: